---
# Master Playbook for wrair servers oscap RHEL7, RHEL8, OEL7 and OEL8
# Christopher Sargent 02142023 

- name: oscap_scans_rhel
  become_user: root
  hosts: all
  tasks:
    - include_role:
        name: oscap_scans_rhel

